*************************
# Environment Variables
*************************

@contentType = application/json
@basepath = api

*************************
## Dev Host
*************************

@hostdev = {{$dotenv HOST_DEV}}
@port = {{$dotenv PORT}}
@dev = http://{{hostdev}}:{{port}}/{{basepath}}

*************************
## Prod Host
*************************

@hostprod = {{$dotenv HOST_PROD}}
@version = v1
@prod = {{hostprod}}/{{basepath}}

*************************
## Token dev mode.
*************************

@tokenDev = {{loginDev.response.body.data.token}}

*************************
## Token prod mode.
*************************

@tokenProd = {{loginProd.response.body.data.token}}

*************************
## Api Key.
*************************

@apiKey = {{$dotenv API_KEY}}

*************************
## Id dev mode.
*************************

@idUserDev = {{getAllUsersDev.response.body.data.users[0]._id}}
@idCarDev = {{getAllCarsDev.response.body.data.cars[0]._id}}
@idTravelDev = {{getAllTravelsDev.response.body.data.travels[0]._id}}

*************************
## Id prod mode.
*************************

@idUserProd = {{getAllUsersProd.response.body.data.users[1]._id}}
@idCarProd = {{getAllCarsProd.response.body.data.cars[0]._id}}
@idTravelProd = {{getAllTravelsProd.response.body.data.travels[0]._id}}

*************************
# Endpoints
*************************

----------------------------------------------
## Docs Route
----------------------------------------------

### dev mode
# @name docsDev
GET {{dev}}/docs

### prod mode.
# @name docsProd
GET {{prod}}/docs HTTP/1.1

----------------------------------------------
## Inavlod route
----------------------------------------------

### dev mode
# @name invalidDev
GET {{dev}}

### prod mode.
# @name invalidProd
GET {{prod}} HTTP/1.1

----------------------------------------------
## Start Route
----------------------------------------------

### dev mode
# @name startDev
GET {{dev}}/

### prod mode.
# @name startProd
GET {{prod}}/ HTTP/1.1

----------------------------------------------
## Auth Route
----------------------------------------------

*************************
## Profile
*************************

### dev mode.
# @name profileDev
GET {{dev}}/auth/profile HTTP/1.1
apikey: {{apiKey}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name profileProd
GET {{prod}}/auth/profile HTTP/1.1
apikey: {{apiKey}}
Authorization: Bearer {{tokenProd}}

*************************
## Register
*************************

### dev mode.
# @name registerDev
POST {{dev}}/auth/register
content-type: {{contentType}}

{
  "email": "core5@coreo.com",
  "password": "1234"
}

### prod mode.
# @name registerProd
POST {{prod}}/auth/register HTTP/1.1
content-type: {{contentType}}

{
  "email": "core5@coreo.com",
  "password": "1234"
}
###
*************************
## Login
*************************

### dev mode
# @name loginDev
POST {{dev}}/auth/login
content-type: {{contentType}}

{
  "email": "coreo@coreo.com",
  "password": "1234"
}

### prod mode.
# @name loginProd
POST {{prod}}/auth/login HTTP/1.1
content-type: {{contentType}}

{
  "email": "coreo@coreo.com",
  "password": "1234"
}
###
----------------------------------------------
## Users route
----------------------------------------------

*************************
## Create User
*************************

### dev mode.
# @name createUserDev
POST {{dev}}/users
Authorization: Bearer {{tokenDev}}

content-type: {{contentType}}

{
  "email": "test1@test.com",
  "password": "1234"
}

### prod mode.
# @name createUserProd
POST {{prod}}/users HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "email": "test2@coreo.com",
  "password": "1234"
}

###
*************************
## Get All Users
*************************

### dev mode.
# @name getAllUsersDev
GET {{dev}}/users
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getAllUsersProd
GET {{prod}}/users HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Get By Id User
*************************

### dev mode
# @name getByIdUserDev
GET {{dev}}/users/{{idUserDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getByIdUserProd
GET {{prod}}/users/{{idUserProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Edit User
*************************

### dev mode
# @name editUserDev
PUT  {{dev}}/users/{{idUserDev}}
Authorization: Bearer {{tokenDev}}
content-type: {{contentType}}

{
  "role": "Admin",
  "name": "dev test"
}

### prod mode.
# @name editUserProd
PUT {{prod}}/users/{{idUserProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "role": "user",
  "name": "prod test"
}
###
*************************
## Delete User
*************************

### dev mode
# @name deleteUserDev
DELETE {{dev}}/users/{{idUserDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name deleteUserProd
DELETE {{prod}}/users/{{idUserProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}

----------------------------------------------
## Car ruote
----------------------------------------------

*************************
## Create Car
*************************

### dev mode.
# @name createCarDev
POST {{dev}}/cars
Authorization: Bearer {{tokenDev}}
content-type: {{contentType}}

{
  "brand": "Chevrolet",
  "model": "Camaro",
  "color": "amarillo",
  "seats": 2,
  "plateCode": "1234",
  "isActive": true
}

### prod mode.
# @name createCarProd
POST {{prod}}/cars HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "brand": "Renault",
  "model": "Clio",
  "color": "red",
  "seats": 4,
  "plateCode": "1234",
  "isActive": true
}

###
*************************
## Get All Cars
*************************
### dev mode.
# @name getAllCarsDev
GET {{dev}}/cars
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getAllCarsProd
GET {{prod}}/cars HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Get By Id Car
*************************

### dev mode

# @name getByIdCarDev
GET {{dev}}/cars/{{idCarDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getByIdCarProd
GET {{prod}}/cars/{{idCarProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Edit Car
*************************

### dev mode
# @name editCarDev
PUT  {{dev}}/cars/{{idCarDev}}
Authorization: Bearer {{tokenDev}}
content-type: {{contentType}}

{
  "color": "blue",
  "seats": 2
}

### prod mode.
# @name editCarProd
PUT {{prod}}/cars/{{:id}} HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "color": "blue",
  "seats": 3
}
###
*************************
## Delete Car
*************************

### dev mode
# @name deleteCarDev
DELETE {{dev}}/cars/{{idCarDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name deleteCarProd
DELETE {{prod}}/cars/{{idCarProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}

----------------------------------------------
## Tarvel Ruotes
----------------------------------------------

*************************
## Create Travel
*************************

### dev mode.
# @name createTravelDev
POST {{dev}}/travels
Authorization: Bearer {{tokenDev}}
content-type: {{contentType}}

{
  "user": "id_User",
  "car": "id_Car",
  "driver": "id_Users",
  "numberSeatsAvailable": 4,
  "numberSeatsOccupied": 0,
  "passengers": {
    "1": null
  },
  "date": "14-12-2023",
  "tripDistance": 234,
  "hometown": "Buenos Aires",
  "provinceOrigen": "Bahia Blanca",
  "sourceAddress": "San Martin 1245",
  "departureTime": "10:00",
  "arrivalCity": "Neuquen",
  "provinceArrival": "Neuquen",
  "checkIn": "14:00",
  "seatCost": 5000,
  "isActive": true
}

### prod mode.
# @name createTravelProd
POST {{prod}}/travels HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "user": "id_User",
  "car": "id_Car",
  "driver": "id_Users",
  "numberSeatsAvailable": 4,
  "numberSeatsOccupied": 0,
  "passengers": {
    "1": null
  },
  "date": "14-12-2023",
  "tripDistance": 234,
  "hometown": "Buenos Aires",
  "provinceOrigen": "Bahia Blanca",
  "sourceAddress": "San Martin 1245",
  "departureTime": "10:00",
  "arrivalCity": "Neuquen",
  "provinceArrival": "Neuquen",
  "checkIn": "14:00",
  "seatCost": 5000,
  "isActive": true
}

###
*************************
## Get All Travels
*************************
### dev mode.
# @name getAllTravelsDev
GET {{dev}}/travels
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getAllTravelsProd
GET {{prod}}/travels HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Get By Id Travel
*************************

### dev mode
@:id= {{idTravelDev}}
# @name getByIdTravelDev
GET {{dev}}/travels/{{idTravelDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name getByIdTravelProd
GET {{prod}}/travels/{{idTravelProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}

*************************
## Edit Travel
*************************

### dev mode
# @name editTravelDev
PUT  {{dev}}/travels/{{idTravelDev}}
Authorization: Bearer {{tokenDev}}
content-type: {{contentType}}

{
  "numberSeatsAvailable": 4,
  "numberSeatsOccupied": 0,
  "tripDistance": 234,
}

### prod mode.
# @name editTravelProd
PUT {{prod}}/travels/{{idTravelProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}
content-type: {{contentType}}

{
  "numberSeatsAvailable": 4,
  "numberSeatsOccupied": 0,
  "tripDistance": 234,
}
###
*************************
## Delete Travel
*************************

### dev mode
# @name deleteTravelDev
DELETE {{dev}}/travels/{{idTravelDev}}
Authorization: Bearer {{tokenDev}}

### prod mode.
# @name deleteTravelProd
DELETE {{prod}}/travels/{{idTravelProd}} HTTP/1.1
Authorization: Bearer {{tokenProd}}