# Environment Variables

@contentType = application/json

## Dev
@hostdev = localhost
@port = 3000
@basepath = api
@dev = http://{{hostdev}}:{{port}}/{{basepath}}

## Prod
@hostprod = https://c17-29-n-node.vercel.app
@basepath = api
@version = v1
@prod = {{hostprod}}/{{basepath}}


### the server in dev mode
get {{dev}}/start HTTP/1.1

### Login User

post {{dev}}/auth/login HTTP/1.1

content-type: application/json

{
  "email": "core2@coreo.com",
  "password": "1234"
}

### the server in prod mode

get {{prod}}/start

### Login User
post {{prod}}/login HTTP/1.1
content-type: {{contentType}}

{
  "email": "core5@coreo.com",
  "password": "1234"
}
